
SELECT DISTINCT name FROM users WHERE NOT age = 36;

SELECT * FROM users WHERE NOT email = 'BLASNJACOBO05@GMAIL.COM'  or age = 15;

SELECT * FROM users WHERE NOT (EMAIL = 'BLASNJACOBO05@GMAIL.COM'  AND age = 15);